[package]
name = "method"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "0.19", default-features = false, features = ["std"] }
core = { path = "../../core" }

serde = { version = "1.0", features = ["derive"] }
